create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  icon text default '📚',
  description text default '',
  color text default '#6366f1',
  total_hours double precision default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  content text default '',
  raw_content text default '',
  subject_id bigint not null references public.subjects(id) on delete cascade,
  tags jsonb default '[]'::jsonb,
  learning_stage text default 'stage1',
  estimated_minutes double precision default 30,
  is_completed boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  product_type text not null,
  content text default '',
  subject_id bigint not null references public.subjects(id) on delete cascade,
  note_id bigint references public.notes(id) on delete set null,
  price_suggestion double precision default 0,
  platform_suggestion jsonb default '[]'::jsonb,
  keywords jsonb default '[]'::jsonb,
  estimated_value text default '',
  export_format text default 'markdown',
  status text default 'draft',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.subjects enable row level security;
alter table public.notes enable row level security;
alter table public.products enable row level security;

drop policy if exists "Users manage own subjects" on public.subjects;
create policy "Users manage own subjects"
  on public.subjects for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage own notes" on public.notes;
create policy "Users manage own notes"
  on public.notes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users manage own products" on public.products;
create policy "Users manage own products"
  on public.products for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists idx_subjects_user_updated on public.subjects(user_id, updated_at desc);
create index if not exists idx_notes_user_subject_updated on public.notes(user_id, subject_id, updated_at desc);
create index if not exists idx_products_user_note_updated on public.products(user_id, note_id, updated_at desc);
