-- Learn2Earn rich-note assets, Skills and background generation tasks.
create table if not exists public.note_assets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  note_id bigint null references public.notes(id) on delete cascade,
  filename text not null,
  media_type text not null default 'application/octet-stream',
  storage_path text not null,
  source_anchor text not null default '',
  size_bytes bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.installed_skills (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text not null default '',
  category text not null default '通用',
  instructions text not null default '',
  storage_path text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, name)
);

create table if not exists public.generation_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  note_id bigint not null references public.notes(id) on delete cascade,
  product_id bigint null references public.products(id) on delete set null,
  product_types jsonb not null default '[]',
  skill_ids jsonb not null default '[]',
  algorithms jsonb not null default '[]',
  techniques jsonb not null default '[]',
  status text not null default 'queued' check (status in ('queued','running','completed','failed')),
  progress integer not null default 0 check (progress between 0 and 100),
  current_step text not null default '等待执行',
  error text not null default '',
  result jsonb not null default '{}',
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists idx_note_assets_user_note on public.note_assets(user_id, note_id);
create index if not exists idx_skills_user_enabled on public.installed_skills(user_id, enabled);
create index if not exists idx_tasks_user_status_updated on public.generation_tasks(user_id, status, updated_at desc);

alter table public.note_assets enable row level security;
alter table public.installed_skills enable row level security;
alter table public.generation_tasks enable row level security;

create policy "users manage own note assets" on public.note_assets for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own skills" on public.installed_skills for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own generation tasks" on public.generation_tasks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
